In [46]:
# Import Libraries and Dependencies
import pandas as pd
from IPython.display import display

### 1. Combine and Clean the Data
#### Import CSVs

In [47]:
# Read the CSV files into DataFrames.
athletic_sales_df_2020 = pd.read_csv('Resources/athletic_sales_2020.csv')
athletic_sales_df_2021 = pd.read_csv('Resources/athletic_sales_2021.csv')

In [48]:
# Display the 2020 sales DataFrame
athletic_sales_df_2020.head()

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000.00,In-store
1,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,68,83,5644,2426.92,Online
2,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,75,275,206250,61875.00,Outlet
3,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,34,384,13056,6789.12,Outlet
4,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,53,83,4399,1407.68,Outlet

In [49]:
# Display the 2021 sales DataFrame
athletic_sales_df_2021.head()

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,65,750,487500,121875.00,Outlet
1,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,51,233,11883,3208.41,Outlet
2,Kohl's,1189833,1/1/21,Midwest,Montana,Billings,Men's Apparel,50,275,137500,82500.00,Outlet
3,Kohl's,1189833,1/1/21,Midwest,Montana,Billings,Men's Apparel,47,77,3619,2714.25,Online
4,West Gear,1128299,1/1/21,West,California,San Francisco,Men's Athletic Footwear,64,225,14400,5184.00,Online

#### Check the data types of each DataFrame

In [50]:
# Check the 2020 sales data types.
display("2020 sales data types:\n", athletic_sales_df_2020.dtypes)

'2020 sales data types:\n'

retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

In [51]:
# Check the 2021 sales data types.
display("2021 sales data types:\n", athletic_sales_df_2020.dtypes)

'2021 sales data types:\n'

retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

#### Combine the sales data by rows.

In [52]:
# Combine the 2020 and 2021 sales DataFrames on the rows and reset the index.
combined_athletic_sales_df = pd.concat([athletic_sales_df_2020, athletic_sales_df_2021], ignore_index=True)
display("combined dataFrame:\n", combined_athletic_sales_df.head())

'combined dataFrame:\n'

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000.00,In-store
1,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,68,83,5644,2426.92,Online
2,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,75,275,206250,61875.00,Outlet
3,Foot Locker,1185732,1/1/20,Northeast,New York,New York,Men's Street Footwear,34,384,13056,6789.12,Outlet
4,Foot Locker,1185732,1/1/20,Northeast,Pennsylvania,Philadelphia,Women's Apparel,53,83,4399,1407.68,Outlet

In [53]:
# Check the data type of each column
data_types = combined_athletic_sales_df.dtypes
print("data typ each column:\n", data_types)

data typ each column:
 retailer             object
retailer_id           int64
invoice_date         object
region               object
state                object
city                 object
product              object
price_per_unit        int64
units_sold            int64
total_sales           int64
operating_profit    float64
sales_method         object
dtype: object

In [54]:
# Convert the "invoice_date" to a datetime datatype
invoice_date_dtype = combined_athletic_sales_df['invoice_date'].dtype

In [55]:
# Confirm that the "invoice_date" data type has been changed.
print("Invoice date data type:", combined_athletic_sales_df['invoice_date'].dtype)

Invoice date data type: object

### 2. Determine which Region Sold the Most Products

#### Using `groupby`

In [56]:
# Show the number products sold for region, state, and city.
sales_by_region = combined_athletic_sales_df.groupby(['region', 'state', 'city'])['units_sold'].sum().reset_index()
# Rename the sum to "Total_Products_Sold".
sales_by_region = sales_by_region.rename(columns={'units_sold': 'Total_Products_Sold'})

# Show the top 5 results.
top_5_sales_by_region = sales_by_region.nlargest(5, 'Total_Products_Sold')
print(top_5_sales_by_region)

       region       state           city  Total_Products_Sold
21  Northeast    New York       New York               111954
33      South       Texas        Houston                90322
44       West  California  San Francisco                85478
43       West  California    Los Angeles                76384
34  Southeast     Florida          Miami                73135

#### Using `pivot_table`

In [57]:
# Show the number products sold for region, state, and city.
pivot_sales_by_region = combined_athletic_sales_df.pivot_table(
    values='units_sold', 
    index=['region', 'state', 'city'],  
    aggfunc='sum'  
).reset_index()


# Rename the "units_sold" column to "Total_Products_Sold"
pivot_sales_by_region = pivot_sales_by_region.rename(columns={'units_sold': 'Total_Products_Sold'})

# Show the top 5 results.
top_5_sales_by_region = sales_by_region.nlargest(5, 'Total_Products_Sold')
print(top_5_sales_by_region)

       region       state           city  Total_Products_Sold
21  Northeast    New York       New York               111954
33      South       Texas        Houston                90322
44       West  California  San Francisco                85478
43       West  California    Los Angeles                76384
34  Southeast     Florida          Miami                73135

### 3. Determine which Region had the Most Sales

#### Using `groupby`

In [58]:
# Show the total sales for the products sold for each region, state, and city.
grouped_sales_region = combined_athletic_sales_df.groupby(['region', 'state', 'city'])['total_sales'].sum().reset_index()

# Rename the "total_sales" column to "Total Sales"
grouped_sales_region = grouped_sales_region.rename(columns={'total_sales': 'Total_Sales'})


# Show the top 5 results.
top_5_sales_by_region = sales_by_region.nlargest(5, 'Total_Products_Sold')
print(top_5_sales_by_region)

       region       state           city  Total_Products_Sold
21  Northeast    New York       New York               111954
33      South       Texas        Houston                90322
44       West  California  San Francisco                85478
43       West  California    Los Angeles                76384
34  Southeast     Florida          Miami                73135

In [67]:
print(combined_athletic_sales_df.columns)

Index(['retailer', 'retailer_id', 'invoice_date', 'region', 'state', 'city',
       'product', 'price_per_unit', 'units_sold', 'total_sales',
       'operating_profit', 'sales_method'],
      dtype='object')

#### Using `pivot_table`

In [69]:
# Show the total sales fr the products sold for each region, state, and city.

print(combined_athletic_sales_df.columns)

# Create a pivot table to sum the sales by Region, State, and City
pivot_sales_region = combined_athletic_sales_df.pivot_table(
    values='total_sales',  # Make sure 'total_sales' is the correct column
    index=['region', 'state', 'city'],  # Group by Region, State, and City
    aggfunc='sum'  # Aggregate using sum
).reset_index()

# Optional: Rename the column to "Total Sales"
pivot_sales_region = pivot_sales_region.rename(columns={'total_sales': 'Total Sales'})

# Show the top 5 results
top_5_pivot_sales_by_region = pivot_sales_region.nlargest(5, 'Total Sales')

# Display the top 5 results
print(top_5_pivot_sales_by_region)

Index(['retailer', 'retailer_id', 'invoice_date', 'region', 'state', 'city',
       'product', 'price_per_unit', 'units_sold', 'total_sales',
       'operating_profit', 'sales_method'],
      dtype='object')
       region           state           city  Total Sales
21  Northeast        New York       New York     39801235
44       West      California  San Francisco     33973228
34  Southeast         Florida          Miami     31600863
39  Southeast  South Carolina     Charleston     29285637
35  Southeast         Florida        Orlando     27682851

### 4. Determine which Retailer had the Most Sales

#### Using `groupby`

In [70]:
# Show the total sales for the products sold for each retailer, region, state, and city.
total_df = combined_athletic_sales_df.groupby(['retailer', 'region', 'state', 'city'])['total_sales'].sum().reset_index()
# Rename the "total_sales" column to "Total Sales"
total_df.rename(columns={'total_sales':'Total_Sales'}, inplace=True)

# Show the top 5 results.
print("top 5 results", total_df.head(5))

top 5 results   retailer     region          state        city  Total_Sales
0   Amazon    Midwest           Ohio    Columbus     16835873
1   Amazon  Northeast          Maine    Portland      8611395
2   Amazon  Northeast  Massachusetts      Boston      4193590
3   Amazon  Northeast  New Hampshire  Manchester     10077142
4   Amazon  Northeast        Vermont  Burlington     13380463

#### Using `pivot_table`

In [72]:
# Show the total sales for the products sold for each retailer, region, state, and city.
pivot_df = combined_athletic_sales_df.pivot_table(index=['retailer', 'region', 'state', 'city'], values='units_sold', aggfunc='sum', fill_value=0).reset_index()

# Optional: Rename the "total_sales" column to "Total Sales"
pivot_df.rename(columns={'total_sales':'Total_Sales'}, inplace=True)

# Show the top 5 results.
display("top 5 results", pivot_df.head(5))

'top 5 results'

  retailer     region          state        city  units_sold
0   Amazon    Midwest           Ohio    Columbus       44925
1   Amazon  Northeast          Maine    Portland       20693
2   Amazon  Northeast  Massachusetts      Boston       11763
3   Amazon  Northeast  New Hampshire  Manchester       26088
4   Amazon  Northeast        Vermont  Burlington       36476

### 5. Determine which Retailer Sold the Most Women's Athletic Footwear

In [74]:
# Filter the sales data to get the women's athletic footwear sales data.
womens_athletic_footwear_sales_df = combined_athletic_sales_df[combined_athletic_sales_df['product'] == 'Women\'s Athletic Footwear']
display(womens_athletic_footwear_sales_df)

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
21,Foot Locker,1185732,1/4/20,Northeast,New York,New York,Women's Athletic Footwear,36,281,10116,3742.92,Outlet
22,Foot Locker,1185732,1/4/20,Northeast,New York,New York,Women's Athletic Footwear,41,247,10127,4658.42,Online
23,Foot Locker,1185732,1/4/20,Northeast,New York,New York,Women's Athletic Footwear,45,850,382500,133875.00,In-store
26,West Gear,1128299,1/5/20,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,45,300,135000,47250.00,Outlet
27,West Gear,1128299,1/5/20,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,34,90,3060,1254.60,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...
9633,Foot Locker,1185732,12/30/21,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,57,53,3021,1601.13,Online
9634,Foot Locker,1185732,12/30/21,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,40,53,2120,954.00,Outlet
9635,Amazon,1185732,12/30/21,Northeast,Maine,Portland,Women's Athletic Footwear,42,36,1512,680.40,Online
9636,Amazon,1185732,12/30/21,Northeast,Maine,Portland,Women's Athletic Footwear,45,125,56250,16875.00,Outlet
9637,Foot Locker,1185732,12/30/21,Northeast,Pennsylvania,Philadelphia,Women's Athletic Footwear,60,175,105000,42000.00,Outlet

#### Using `groupby`

In [19]:
# Show the total number of women's athletic footwear sold for each retailer, region, state, and city.
grouped_df = womens_athletic_footwear_sales_df.groupby(['retailer', 'region', 'state', 'city'])['units_sold'].sum().reset_index()

# Rename the "units_sold" column to "Womens_Footwear_Units_Sold"

grouped_df.rename(columns={'units_sales':'Womens_Footwear_Units_Sold'}, inplace=True)

# Show the top 5 results.
print("top 5 results", grouped_df.head(5))

                                                      Womens_Footwear_Units_Sold
retailer      region    state          city
West Gear     West      California     San Francisco                       12107
Foot Locker   Northeast New York       New York                            10996
Kohl's        West      California     Los Angeles                         10826
Foot Locker   Southeast South Carolina Charleston                           8814
Sports Direct South     Texas          Dallas                               8790

#### Using `pivot_table`

In [85]:
# Show the total number of women's athletic footwear sold for each retailer, region, state, and city.

womens_athletic_footwear_sales_df = combined_athletic_sales_df[combined_athletic_sales_df['product'] == 'Womens athletic footwear sold']


# Rename the "units_sold" column to "Womens_Footwear_Units_Sold"
pivot_sales_womens_footwear = pivot_sales_womens_footwear.rename(columns={'units_sold': 'Womens_Footwear_Units_Sold'})

# Show the top 5 results.
display("top 5 results", grouped_df.head(5))

'top 5 results'

    region     state          city  units_sold
0  Midwest  Illinois       Chicago       25407
1  Midwest   Indiana  Indianapolis       26332
2  Midwest      Iowa    Des Moines       23446
3  Midwest    Kansas       Wichita       29463
4  Midwest  Michigan       Detroit       50095

### 6. Determine the Day with the Most Women's Athletic Footwear Sales

In [89]:
# Create a pivot table with the 'invoice_date' column is the index, and the "total_sales" as the values.
pivot_sales_by_date = combined_athletic_sales_df.pivot_table(
    values='total_sales',  # Summing the total_sales
    index='invoice_date',  # Using invoice_date as the index
    aggfunc='sum'  # Aggregating using sum
).reset_index()

# Optional: Rename the 'total_sales' column to 'Total Sales'
pivot_sales_by_date = pivot_sales_by_date.rename(columns={'total_sales': 'Total Sales'})

# Show the pivot table
display(pivot_sales_by_date)

    invoice_date  Total Sales
0         1/1/20       845141
1         1/1/21       654902
2        1/10/20       200469
3        1/10/21      3675792
4        1/11/20       129556
..           ...          ...
718       9/7/21      1120330
719       9/8/20       726106
720       9/8/21      2683674
721       9/9/20       814562
722       9/9/21      2008803

[723 rows x 2 columns]

In [93]:
# Resample the pivot table into daily bins, and get the total sales for each day.

combined_athletic_sales_df['invoice_date'] = pd.to_datetime(combined_athletic_sales_df['invoice_date'])

# Create a pivot table with 'invoice_date' as the index and 'total_sales' as the values
pivot_sales_by_date = combined_athletic_sales_df.pivot_table(
    values='total_sales',  # Summing the total_sales
    index='invoice_date',  # Using invoice_date as the index
    aggfunc='sum'  # Aggregating using sum
).reset_index()

# Optional: Rename the 'total_sales' column to 'Total Sales'
pivot_sales_by_date = pivot_sales_by_date.rename(columns={'total_sales': 'Total Sales'})

# Convert 'invoice_date' column to datetime (in case it's still not in datetime format)
pivot_sales_by_date['invoice_date'] = pd.to_datetime(pivot_sales_by_date['invoice_date'])

# Set 'invoice_date' as the index for resampling
pivot_sales_by_date.set_index('invoice_date', inplace=True)

# Resample the data into daily bins and sum the total sales for each day
resampled_sales = pivot_sales_by_date.resample('D').sum()


# Sort the resampled pivot table in descending order on "Total Sales".
sorted_resampled_sales = resampled_sales.sort_values('Total Sales', ascending=False)

# Display the sorted resampled sales
display(sorted_resampled_sales)

              Total Sales
invoice_date
2021-07-16       12261098
2021-12-16       10871121
2021-06-17       10239903
2021-08-17        9517031
2021-07-23        7689134
...                   ...
2020-10-16              0
2020-10-15              0
2020-10-14              0
2020-10-13              0
2020-12-31              0

[731 rows x 1 columns]